### ISSUE TITLE
Can't install plugin (iconv installation error)

### ISSUE THREAD

**Issue by xgodon** [aspiresoftware/redmine-import-tasks#15]
Hello,

I'm looking to install your plugin. I run redmine with docker in this environnement :

Environment:
  Redmine version                3.0.7.stable
  Ruby version                   2.2.5-p319 (2016-04-26) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem  
Redmine plugins:
  redcase                        1.0
  redmine_agile                  1.4.0

After `git clone https://github.com/aspiresoftware/redmine-import-tasks.git issue_importer_xls`

---

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Using rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using rack 1.6.4
Using mime-types-data 3.2016.0521
Using arel 6.0.3
Using bundler 1.12.4
Using coderay 1.1.1
Using concurrent-ruby 1.0.2
Using htmlentities 4.3.1
Installing iconv 1.0.4 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
current directory: /usr/local/bundle/gems/iconv-1.0.4/ext/iconv
```

/usr/local/bin/ruby -r ./siteconf20160726-8-1hn1mqt.rb extconf.rb
checking for rb_enc_get() in ruby/encoding.h... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-iconv-dir
        --without-iconv-dir
        --with-iconv-include
        --without-iconv-include=${iconv-dir}/include
        --with-iconv-lib
        --without-iconv-lib=${iconv-dir}/lib
        --enable-config-charset
        --disable-config-charset
        --with-config-charset
        --without-config-charset
/usr/local/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:541:in`try_link0'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:735:in`try_func'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:1020:in `block in have_func'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:911:in`block in checking_for'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:321:in`open'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:321:in`open'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:910:in`checking_for'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:1019:in `have_func'
        from extconf.rb:8:in`<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/2.2.0-static/iconv-1.0.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/iconv-1.0.4 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.2.0-static/iconv-1.0.4/gem_make.out
Using thor 0.19.1
Using mysql2 0.3.21
Using net-ldap 0.3.1
Using ruby-openid 2.3.0
Using redcarpet 3.3.4
Using request_store 1.0.5
Using rmagick 2.13.4
Using rubyzip 1.2.0
Using ruby-ole 1.2.12
Using tzinfo 1.2.2
Using nokogiri 1.6.7.2
Using rack-test 0.6.3
Using mime-types 3.1
Using sprockets 3.6.0
Using rbpdf 1.18.7
An error occurred while installing iconv (1.0.4), and Bundler cannot continue.

> Make sure that `gem install iconv -v '1.0.4'` succeeds before bundling.

---

I'm not familiar with redmine, could you help me resolve this issue?

**Comment by xgodon** [comment]
the log file : 

root@41befdf5222e:/opt# cat /usr/local/bundle/extensions/x86_64-linux/2.2.0-static/iconv-1.0.4/mkmf.log
"gcc -o conftest -I/usr/local/include/ruby-2.2.0/x86_64-linux -I/usr/local/include/ruby-2.2.0/ruby/backward -I/usr/local/include/ruby-2.2.0 -I.     -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -L/usr/local/lib -Wl,-R/usr/local/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-R/usr/local/lib -L/usr/local/lib -lruby-static  -lpthread -ldl -lcrypt -lm   -lc"
checked program was:
/\* begin _/
1: #include "ruby.h"
2:
3: int main(int argc, char *_argv)
4: {
5:   return 0;
6: }
/\* end */

**Comment by ava5412** [comment]
same problem =(

**Comment by vrstud** [comment]
I was able to resolve the issue by following the advice here:
http://stackoverflow.com/questions/28558578/error-while-installing-iconv-on-windows-by-ruby2-0-0

I had this problem this evening (Windows 7, Ruby 1.9.3). The solution in my case was as follows:
    Install the "Complete package, except sources" from http://gnuwin32.sourceforge.net/packages/libiconv.htm
    Run gem install iconv -v '1.0.4' -- --with-iconv-dir=/path/to/GnuWin32
