### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by jleecbd** [aspiresoftware/redmine-import-tasks#8]
Clone, followed by bundle install results in the following error message:

cannot load such file -- spreadsheet/errors (LoadError)
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`block in require'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`require'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/spreadsheet-0.9.9/lib/spreadsheet.rb:27:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in`require'
  /usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
  /usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in`each'
  /usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
  /usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in`each'
  /usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
  /usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler.rb:132:in`require'
  /usr/local/share/redmine-2.5.0/config/application.rb:7:in `<top (required)>'
  /usr/local/share/redmine-2.5.0/config/environment.rb:2:in`require'
  /usr/local/share/redmine-2.5.0/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in`require'
  config.ru:3:in `block in <main>'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/builder.rb:51:in`instance_eval'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in`new'
  config.ru:1:in `<main>'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/passenger-4.0.17/helper-scripts/rack-preloader.rb:105:in`eval'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/passenger-4.0.17/helper-scripts/rack-preloader.rb:105:in `preload_app'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/passenger-4.0.17/helper-scripts/rack-preloader.rb:150:in`module:App'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/passenger-4.0.17/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/passenger-4.0.17/helper-scripts/rack-preloader.rb:28:in`<main>'

**Comment by sacbalz** [comment]
I was able to get around this error by editing the spreadsheet.rb
cd /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/spreadsheet-0.9.9/lib/
nano spreadsheet.rb
change spreadsheet/errors to spreadsheet/excel/error
note the s at the end
ruby bin/rake redmine:plugins RAILS_ENV=production
sudo /opt/bitnami/ctlscript.sh restart

The plugin installed correctly and I see no entries in the error log, but whenever I submit a file I get an Internal Error 500
I can't use this anyway. I need an importer that will handle parent tasks

**Comment by dominch** [comment]
Change plugins/issue_importer_xls/Gemfile to: 

<pre>
source 'https://rubygems.org'
if RUBY_VERSION >= "1.9"
      gem 'roo'
      gem 'iconv'.
      gem 'spreadsheet',"~> 1.0.3"
end
</pre>

(spreadsheets versio)

**Comment by xJom** [comment]
Still not working, even if you update to spreadsheet 1.0.3.
You get:
An error occured while loading the routes definition of of issue_importer_xls plugin (path/to/routes.rb): You should not use the match method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add 'via: [:get, :post]' option.
If you want to expose your action to GET, use 'get' in the router.
   Instead of: match "controller#action"
   Do: get "controller#action"
Exiting

Adding ", via: [:get, :post]" after each of the three match-lines in routes.rb makes it work.

I'll add a Pull Request shortly.

**Comment by janekska** [comment]
I have the same problem.

My setup:
Environment:
  Redmine version                3.0.3.stable
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.0.2
  Git                            1.7.9.5
  Filesystem  
Redmine plugins:
  accept                         0.0.1
  event_notifications            3.0.0
  redmine_dashboard              2.5.0
  redmine_mail_reminder          3.0.0.0001
  redmine_spent_time_in_issue_description 2.7
  redmine_theme_changer          0.2.0
  redmine_timelog_timer          2.0.1
  redmine_work_time              0.3.1

I have spreadsheet v.9.9.
I changed plugins/issue_importer_xls/Gemfile to this version above, but it does not help.

**Comment by jasonfharris** [comment]
For what it is worth. I just hit the same error. Seeing as others above have investigated this and it still isn't working then I am giving up on this until a fix by the authors...

**Comment by badpenguin** [comment]
@xJom i've the same issue
@jasonfharris same :-/

**Comment by xJom** [comment]
vichaks fork works excellent. We are using it for production. Please download it here: https://github.com/vichak/redmine-import-tasks
